[package]
name = "messaging"
edition = "2024.beta"

[dependencies]
permissioned_groups = { local = "../permissioned-groups" }
suins = { git = "https://github.com/MystenLabs/suins-contracts", subdir = "packages/suins", rev = "2b75990bdc31472405a6bf47b40152627a1fa6c0" }

[addresses]
messaging = "0x0"

[dev-addresses]

[environments]
mainnet = { chain-id = "35834a8a" }
testnet = { chain-id = "4c78adac" }